name: tests and lint

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install python
        uses: actions/setup-python@v3
        with:
          python-version: ^3.10

      - name: Install dependencies
        run: |
          pip install poetry
          make install

      - name: Drop existing test database
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: |
          psql "${{ secrets.DATABASE_URL }}" -c "DROP DATABASE IF EXISTS test_django_db_bbv9;"

      - name: Run lint
        run: |
          make lint

      - name: Run tests
        env:
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEBUG: True
        run: |
          make test

      - name: Run code coverage
        uses: paambaati/codeclimate-action@v3.2.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CC_TEST_REPORTER_ID }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ROLLBAR_KEY: ${{ secrets.ROLLBAR_KEY }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          DEBUG: True
        with:
          coverageCommand: make test-coverage
          debug: true